In [1]:
from __future__ import division
from numpy.random import randn
import numpy as np
import os
import matplotlib.pyplot as plt
np.random.seed(12345)
plt.rc('figure', figsize=(10, 6))
from pandas import Series, DataFrame
import pandas as pd
np.set_printoptions(precision=4)

In [3]:
obj = Series([4,7,-5,3],index=['d','b','a','c']) #must be Capital Series
obj

d    4
b    7
a   -5
c    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [6]:
obj['d']

4

In [7]:
obj[obj>0]

d    4
b    7
c    3
dtype: int64

In [8]:
obj*2

d     8
b    14
a   -10
c     6
dtype: int64

In [9]:
np.exp(obj)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [10]:
sdata={'Ohio':3500, 'Texas':7100, 'Oregon':1600, 'Utah':500}
obj2=Series(sdata)

In [11]:
obj2

Ohio      3500
Oregon    1600
Texas     7100
Utah       500
dtype: int64

In [22]:
states=['California','Ohio','Oregon', 'Texas']
obj3=Series(sdata,index=states)
obj3

California       NaN
Ohio          3500.0
Oregon        1600.0
Texas         7100.0
dtype: float64

In [13]:
pd.isnull(obj3)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [14]:
pd.notnull(obj3)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [18]:
obj2+obj3

California        NaN
Ohio           7000.0
Oregon         3200.0
Texas         14200.0
Utah              NaN
dtype: float64

In [23]:
obj3

California       NaN
Ohio          3500.0
Oregon        1600.0
Texas         7100.0
dtype: float64

In [24]:
obj3.name='population'
obj3.index.name='state'
obj3

state
California       NaN
Ohio          3500.0
Oregon        1600.0
Texas         7100.0
Name: population, dtype: float64

In [25]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [26]:
DataFrame(data, columns=['year','state','pop'])


year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [27]:
DataFrame(data, columns=['year','state','pop','zip'])


year   state  pop  zip
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN

In [29]:
data = DataFrame(np.arange(16).reshape((4, 4)),
                 index=['Ohio', 'Colorado', 'Utah', 'New York'],
                 columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [30]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [31]:
data.ix[2]

/Anaconda/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [36]:
data.iloc[0] #the 1st row 

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int64

In [37]:
data.loc['Ohio'] #the 'Ohio' row

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int64

In [38]:
df1 = DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                index=['Ohio', 'Texas', 'Colorado'])
df2 = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                index=['Utah', 'Ohio', 'Texas', 'Oregon'])
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [39]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [40]:
df1.add(df2,fill_value=0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [45]:
df1 = DataFrame(np.arange(12.).reshape((3, 4)), columns=list('bcda'))
df2 = DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))
df1

b    c     d     a
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [47]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [48]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   3.0   1.0   3.0   5.0   4.0
1  12.0  10.0  12.0  14.0   9.0
2  21.0  19.0  21.0  23.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [46]:
df1.reindex(columns=df2.columns,fill_value=0)

a    b    c     d  e
0   3.0  0.0  1.0   2.0  0
1   7.0  4.0  5.0   6.0  0
2  11.0  8.0  9.0  10.0  0

In [49]:
arr=np.arange(12.).reshape(3,4)
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [50]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [51]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [52]:
frame = DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                  index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [54]:
f = lambda x: x.max() - x.min()

In [55]:
frame.apply(f)

b    9.0
d    9.0
e    9.0
dtype: float64

In [56]:
frame.apply(f, axis=1)

Utah      2.0
Ohio      2.0
Texas     2.0
Oregon    2.0
dtype: float64

In [58]:
def f(x):
    return Series([x.min(),x.max(),x.var(),x.mean()], index=['min','max','var','mean'])

frame.apply(f)
# here we would get the sample variance=E(x-x.bar)2/(n-1)

b     d     e
min    0.0   1.0   2.0
max    9.0  10.0  11.0
var   15.0  15.0  15.0
mean   4.5   5.5   6.5

In [60]:
frame.describe()

b          d          e
count  4.000000   4.000000   4.000000
mean   4.500000   5.500000   6.500000
std    3.872983   3.872983   3.872983
min    0.000000   1.000000   2.000000
25%    2.250000   3.250000   4.250000
50%    4.500000   5.500000   6.500000
75%    6.750000   7.750000   8.750000
max    9.000000  10.000000  11.000000

In [63]:
format = lambda x: '%.2f' %x
frame.applymap(format)

b      d      e
Utah    0.00   1.00   2.00
Ohio    3.00   4.00   5.00
Texas   6.00   7.00   8.00
Oregon  9.00  10.00  11.00

In [64]:
frame['e'].map(format)

Utah       2.00
Ohio       5.00
Texas      8.00
Oregon    11.00
Name: e, dtype: object

In [67]:
obj=Series(range(4),index=list('badc'))
obj

b    0
a    1
d    2
c    3
dtype: int64

In [68]:
obj.sort_index()

a    1
b    0
c    3
d    2
dtype: int64

In [69]:
obj

b    0
a    1
d    2
c    3
dtype: int64

In [70]:
frame = DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
                  columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [71]:
frame.sort_index() #sort row number

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [72]:
frame.sort_index(axis=1) #sort column number ascending

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [73]:
frame.sort_index(axis=1, ascending=False) # sort column number descending

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [74]:
obj2=Series([4,-3,3,5])
obj2

0    4
1   -3
2    3
3    5
dtype: int64

In [79]:
sorted(obj2)

[-3, 3, 4, 5]

In [80]:
obj = Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [81]:
mask = obj.isin(['b','c'])
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object